### ISSUE TITLE
GDPR infringement

### ISSUE THREAD

**Issue by rschrenk** [h5p/h5p-php-library#116]
Hello,

we recognized, that this part of the mod_hvp-Plugin uses Google APIs in the following files:
- https://github.com/h5p/h5p-php-library/blob/c79f97a16fd8c6fc0232c10d5bed5b94502ee9e9/styles/h5p-hub-sharing.css#L1
- https://github.com/h5p/h5p-php-library/blob/c79f97a16fd8c6fc0232c10d5bed5b94502ee9e9/styles/h5p-hub-registration.css#L1

As for European sites, this causes an infringement of the GDPR. Would it be possible to fix that?

Kind regards

**Comment by fnoks** [comment]
Thank you for reporting this. We will fix this in the next mod_hvp release.
