### ISSUE TITLE
"We will make available documentation and tutorials for creating platform integrations in the future."

### ISSUE THREAD

**Issue by IpelaTech** [h5p/h5p-php-library#127]
Are there any follow-ups on this? 

I've already spent 2 weeks trying to make headway using the Wordpress plugin, and some of the Laravel plugins (I'm using Laravel) and they're mostly out-of-date or just don't work. I can't spend another week _trying_ to figure things out.

I'd love to contribute, but I have no idea how the plugin works and I can't spend much more time debugging and writing tests, I have other features to implement on my LMS. Even a decent overview/summary so I can get the ball rolling, then I can document and contribute as I go and help solve this permanently, I'm willing to do that! 

If there's no feedback, can someone suggest an alternative library?

Thanks.

**Comment by IpelaTech** [comment]
Please delete. Thanks.

**Comment by deborahshda** [comment]
Hi, were you able to integrate with laravel?
