### ISSUE TITLE
Allow using HTML tags MARK and ABBR in H5P content types

### ISSUE THREAD

**Issue by dosse** [h5p/h5p-php-library#142]
Hello,
I'm using your great tool for the setup of a training course, and would need a few specific harmless HTML tags that are useful in this context.

Would it please be possible to allow for additional HTML tags `mark` to highlight words (e.g. `<mark>highlighted text</mark>`) and `abbr/title` to add a tooltip (e.g. `<abbr title="tooltip text">text with tooltip</abbr>`)?

While I can currently copy/paste such formatted text into the image description edit field of the Agamotto content type (Version 6.1.1 in WordPress):  
![image](https://user-images.githubusercontent.com/1862608/215093289-4ad33e60-d5e0-4eaf-9146-aa6f27fada4e.png)

once it is saved and displayed this formatting currently gets lost:  
![image](https://user-images.githubusercontent.com/1862608/215093526-7e85661a-e358-470a-b59b-fe3e0a6d8943.png)

Or maybe you could point me please to alternative approaches to achieve this?
Thanks in advance for your help.

----------------
Reference: https://github.com/otacke/h5p-agamotto/issues/390  
https://h5p.org/semantics#attribute-tags

**Comment by boyum** [comment]
By adding `mark` and `abbr` to the list of `tags` on the field in the content type's semantics, these tags can be used. In this case, I've typed in `<mark>marked text</mark>` and `<abbr title="abbreviation">abbr</abbr>` to the text field, which seems to work as expected.

<img width="132" alt="image" src="https://user-images.githubusercontent.com/9085189/215333773-4842d13b-c72c-40f3-be22-519f11e659eb.png">

:warning: the tags are not mentioned in [the docs](https://h5p.org/semantics#attribute-tags), and might not be _officially_ supported.

**Comment by otacke** [comment]
Adding additional tags would prevent them from being filtered out (in https://github.com/h5p/h5p-editor-php-library/blob/master/scripts/h5peditor-html.js#L523-L531), but the editor would not display corresponding buttons for adding them (https://github.com/h5p/h5p-editor-php-library/blob/master/scripts/h5peditor-html.js#L38).

It would be up to the content type author to allow them, but there's no guarantee that the current handler will remain the same (in particular once the CKEditor gets replaced), so I am going to stick to the [list of tags in the specification](https://h5p.org/semantics#attribute-tags).

/cc @boyum

**Comment by dosse** [comment]
@boyum @otacke Thank you for your responses. I do actually **not** need the editor to display the corresponding buttons to use these tags in the content text. For me it's easy enough to copy/paste the already formatted text into the editor. I would only need these tags to not be stripped out again. I'm unsure to where the changes need to be done if we talk about the Agamotto content type: 
- Here?: [tags in Agamotto image descriptions](https://github.com/otacke/h5p-agamotto/blob/a543b4435709929afa785a196b099632615e5095/semantics.json#L60)
- Here?: [default tags in h5p editor](https://github.com/h5p/h5p-editor-php-library/blob/53dc7bdc57b17f5a0d55a8871a36d1b1bd631e70/scripts/h5peditor-html.js#L20)

And I'm also unsure who could do these changes? Would you be able to make these additions in your source code,  would I (or our hosting company) need to fork away or would this be a simple configuration change in our instance https://academy.siscc.org/? 

Thanks again for your kind help on this.

**Comment by otacke** [comment]
@dosse I fully understood that. You don't need them. But obviously H5P Group tries not to have too many "hidden features" that are not obvious to the common user.

As I said, I am going to stick to the [list of tags in the specification](https://h5p.org/semantics#attribute-tags). But you can fork or simply use H5P's [Authoring tool customization](https://h5p.org/documentation/for-developers/authoring-tool-customization) and add those tags via hooks. No need to touch any of the original code or to live with a fork, but if you share the content, on other platforms the extra tags will be filtered out.

**Comment by dosse** [comment]
@otacke Thanks for the quick response! We will try your suggestion.
