### ISSUE TITLE
Is library version checking working properly?

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-php-library#15]
**Expected behavior:**

Content package requires library version 4.1. The system has 4.5.2, so everything should work.

**Actual behavior:**

I'm getting the error:
> Missing required library foo 4.1

Is this working as intended?

**Comment by falcon-git** [comment]
Yes, you could have a higher patch version, but not a higher minor. We will make changes related to this in the future.

**Comment by juho-jaakkola** [comment]
Ok, closing as WAI.

Related question: https://h5p.org/comment/4028#comment-4028
