### ISSUE TITLE
Publish core API version 1.27

### ISSUE THREAD

**Issue by thibsy** [h5p/h5p-php-library#192]
Hi folks,

There are currently many content types or libraries, which can be downloaded from your hub, that require a minimum core-API version of 1.27. However, this version is not available on [packagist.org](https://packagist.org/packages/h5p/h5p-core) and on GitHub there is only an official release of this version specific to Moodle.

I therefore ask you to publish the latest version for other integrations as well, because they cannot import, install or update content types or libraries anymore.

Kind regards,
@thibsy

**Comment by ymdahi** [comment]
Bumping.

Please provide an update on when 1.27 will be available (Drupal is my specific interest). We are starting to get complaints about inter-operability. 

With Thanks, Yasin

**Comment by thibsy** [comment]
The version 1.27.0 has been officially released on [packagist](https://packagist.org/packages/h5p/h5p-core), I therefore close the issue.
