### ISSUE TITLE
xapi - add additional context activity representing the CMS page that the content exists on

### ISSUE THREAD

**Issue by garemoko** [h5p/h5p-php-library#3]
It would be helpful to group H5P interactions that occur on a single page together with a context activity grouping. Is there any way we can fetch the id (or url) of the current CMS page and use that as a grouping context activity? 

I'm guessing it would go in [this function](https://github.com/h5p/h5p-php-library/blob/cb8640195ebd8b0f8c3903ae6a831a7bc66966a1/js/h5p-x-api-event.js#L129).

**Comment by falcon-git** [comment]
I can see how this might be useful. I'm not sure if that is something H5P core should do. Is this something everyone will want? You might do this prior to sending the statements to the LRS in your own code instead? Then you can probably use CMS specific functions for the url too. A generic approach would probably have to be based on window.location, or rely on something that all CMSs that implements H5P will have to implement.

**Comment by garemoko** [comment]
It's the kind of thing that nobody will **want** until they realise after 6 months of data collection that they need it for reporting :-) 

There probably does need to be some CMS specific code to determine the variable and then perhaps core code to add the property? I couldn't see anything in the [Wordpress plugin](https://github.com/h5p/h5p-wordpress-plugin) that does anything with xAPI. 

Perhaps I'm looking at the wrong plugin and the code should go [here](https://github.com/tunapanda/wp-h5p-xapi/blob/master/process-xapi-statement.php#L15) or [here](https://github.com/tunapanda/wp-h5p-xapi/blob/master/wp-h5p-xapi.js#L76)? In that case, maybe the core doesn't need to change. Are there equivalent plugins for the other CMSs?

**Comment by falcon-git** [comment]
Yeah, it probably belongs in that plugin :)

There is a similar one for Drupal:
https://www.drupal.org/project/h5p_tincan_bridge

**Comment by garemoko** [comment]
Ok. I will close this issue here then.
