### ISSUE TITLE
Fullscreen in Safari 10 not working

### ISSUE THREAD

**Issue by peteresser** [h5p/h5p-php-library#34]
Hi There,

First of all; great work guys, really like your elements and components. We hope to contribute in the near future. A customer was reporting issues with Safari 10 and fullscreen. After debugging I also came across this drupal website, where a user has found the root cause and solution.

https://www.drupal.org/node/2805311

The problem is the detection of the Safari version. As they now have version 10 (2 digits), your regular expression is only taking 1 digit, so it sees it as Safari < 7 and no real full screen is enabled. But is also not enabling the semi full screen modus (as @paalj there is asking), thus the button is not doing anything.

Version 8 and 9 of Safari are working fine, as I just checked it with Browserstack.
Can you please fix this in your main h5p.org distribution as embeds from H5P are not working with full screen in Safari 10?

If I can assist in any way, let me know.

Peter

**Comment by peteresser** [comment]
Fix found and made by lestt added as reference:

`
-  H5P.safariBrowser = navigator.userAgent.match(/Version\/(\d)/);
+  H5P.safariBrowser = navigator.userAgent.match(/version\/([\.\d]+)/i);
`

**Comment by fnoks** [comment]
Thank you for your investigations, and for providing a patch. We will add it ASAP.

**Comment by thomasmars** [comment]
This has been fixed and commited to ['master' branch of library](https://github.com/h5p/h5p-php-library/commit/d76ce3f3a567b132c5626622d294d84f10a60cad), and should be included in the upcoming release.
