### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by svarlamov** [h5p/h5p-php-library#49]
Not sure that this is the best place to record this issue, but the h5p.org site (where the docs used to be) has been down for the last 14 hours (at least). The google cached version is pretty hard to use, so it'd be great to have an estimate on when we can expect to have the site back up. Thank you!

**Comment by otacke** [comment]
Hi Sasha!

I​t's an issue with our host Digital Ocean. Their block storage service is down. They have found the problem and are working on a fix: https://status.digitalocean.com/incidents/8sk3mbgp6jgl
Unfortunately, there's nothing that we can do but wait (and consider replacing Digital Ocean) :/ Fortunately, we'll have our own failovers for the upcoming h5p.com. 

Best,
Oliver

**Comment by svarlamov** [comment]
@otacke Sounds great -- thank you for the update!
