### ISSUE TITLE
Integration with my own PHP code/framework

### ISSUE THREAD

**Issue by ShinJii89** [h5p/h5p-php-library#55]
Hi,
You're saying in documentation that if I want to use h5p on my website I have to install plugin for wordpress/moodle/drupal... and I'm confused :P - Can I integrate h5p with my framework in php (creating h5p files, integrate plugins like flashcards etc.) ? or it's only for wordpress/moodle/drupal?

**Comment by otacke** [comment]
Hi ShinJii89!

I am not sure if I understand your question. Sure, if you're versatile enough and implement your own interface between your host system and the H5P core (basically your own plugin handling e.g. calls to the database and the file system), that will work, too.

Best,
Oliver

**Comment by otacke** [comment]
No, unfortunately not yet. You'd probably have to choose one of the plugins for other host systems (that's closest to yours) and try to replicate what it does.

**Comment by ShinJii89** [comment]
Yeah... I thought I would have to analyze the code from your plugins - thanks for reply :)
