### ISSUE TITLE
Document the git branches

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-php-library#7]
Currently the repo has multiple branches that do not really make sense:
 - auto-install
 - d6
 - editor-padding
 - etc...

Based on the names these seem like feature branches. Branches in the main repo should* instead be used for telling apart versions that are not compatible with each other:
 - 1.x.x
 - 2.x.x (Contains changes not compatible with 1.x.x)
 - 3.x.x (Contains changes not compatible with 2.x.x)
 - etc...

Or at least it should be documented somewhere, what each of the current branches is used for. (What would be the best place for this kind of documentation?)

*Absolute Truth™ ;)

**Comment by falcon-git** [comment]
Thank you for the feedback. Currently it is like this:

stable holds released code and is tagged with where it is released, so Drupal-7.x-1.11 would mean that it is part of the Drupal 7.x-1.11 module.

master holds all the newest runnable code.

release holds code that is about to be released - typically used actively when regression testing.

Then you have feature branches.

We will reconsider this based on your feedback, and perhaps the readme file is a good place to document it?

**Comment by juho-jaakkola** [comment]
The Github wiki might in fact be better than readme, because readme is version specific and should only contain info that is relevant to each particular version.

**Comment by falcon-git** [comment]
Ok, I've added the info to the Wiki

**Comment by juho-jaakkola** [comment]
Thanks!
