### ISSUE TITLE
Submit the library to Packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-php-library#8]
Now that #6 has been merged, would it also be possible to submit the library to https://packagist.org/?

This way a project that uses the library as a dependency wouldn't have to explicitly define the vcs URL in its own composer.json, but composer would automatically find the package from Packagist.

I noticed that there isn't yet 'h5p' namespace in Packagist. When submittin the package, please note that the first user to submit a package to a namespace automatically becomes it's owner for all eternity (or at least Packagist currently does not have a feature to allow changing the ownership.)

**Comment by icc** [comment]
We should probably have a clean-up before publishing it. Like putting the classes in separate files, and making sure the documentation is up-to-date.

**Comment by juho-jaakkola** [comment]
Packagist supports also development code. So as long as it's clearly declared (e.g. version `1.2.0-dev`) there is no problem.

But there is no rush. Might as well do some overhaul before submitting.

**Comment by marclaporte** [comment]
+1 as this will make it easier to adopt H5P :-)

Thanks!

**Comment by MichielDilissen** [comment]
+1

**Comment by marclaporte** [comment]
Please see: https://packagist.org/packages/h5p/

**Comment by beheist** [comment]
Looks like this can be closed, no? I was able to install the h5p libs via composer without any issue.

**Comment by icc** [comment]
Correct, thank you!

**Comment by marclaporte** [comment]
Already over 12 000 installs!  H5P is awesome!
